/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.src1.view;

import com.example.src1.controller.TinhDiem_controller;

/**
 *
 * @author admin
 */
public class GiaoDienTinhDiem_Frame extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienTinhDiem_Frame
     */
    public GiaoDienTinhDiem_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lost_win = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ViTri2 = new javax.swing.JLabel();
        ViTri3 = new javax.swing.JLabel();
        XepThu2 = new javax.swing.JTextField();
        XepThu3 = new javax.swing.JTextField();
        QuayVe = new javax.swing.JButton();
        XepThu1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(24, 34, 56));

        jPanel1.setBackground(new java.awt.Color(24, 34, 56));

        lost_win.setEditable(false);
        lost_win.setBackground(new java.awt.Color(204, 255, 204));
        lost_win.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lost_win.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lost_win.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 0, 0), new java.awt.Color(0, 255, 0)));

        jPanel2.setLayout(null);

        ViTri2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man_1.png"))); // NOI18N
        jPanel2.add(ViTri2);
        ViTri2.setBounds(40, 220, 130, 130);

        ViTri3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/woman.png"))); // NOI18N
        jPanel2.add(ViTri3);
        ViTri3.setBounds(370, 260, 130, 140);

        XepThu2.setEditable(false);
        XepThu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        XepThu2.setForeground(new java.awt.Color(153, 0, 255));
        XepThu2.setBorder(null);
        jPanel2.add(XepThu2);
        XepThu2.setBounds(60, 340, 100, 19);

        XepThu3.setEditable(false);
        XepThu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        XepThu3.setForeground(new java.awt.Color(153, 0, 255));
        XepThu3.setBorder(null);
        jPanel2.add(XepThu3);
        XepThu3.setBounds(390, 390, 100, 19);

        QuayVe.setBackground(new java.awt.Color(0, 255, 51));
        QuayVe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        QuayVe.setForeground(new java.awt.Color(102, 0, 204));
        QuayVe.setText("QUAY VỀ");
        QuayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuayVeActionPerformed(evt);
            }
        });
        jPanel2.add(QuayVe);
        QuayVe.setBounds(210, 600, 110, 29);

        XepThu1.setEditable(false);
        XepThu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        XepThu1.setForeground(new java.awt.Color(102, 0, 204));
        XepThu1.setBorder(null);
        jPanel2.add(XepThu1);
        XepThu1.setBounds(170, 50, 210, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/podium.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 80, 512, 502);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lost_win, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lost_win, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuayVeActionPerformed
        this.dispose();
        new TinhDiem_controller();
    }//GEN-LAST:event_QuayVeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GiaoDienTinhDiem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GiaoDienTinhDiem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GiaoDienTinhDiem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GiaoDienTinhDiem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GiaoDienTinhDiem_Frame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuayVe;
    private javax.swing.JLabel ViTri2;
    private javax.swing.JLabel ViTri3;
    public javax.swing.JTextField XepThu1;
    public javax.swing.JTextField XepThu2;
    public javax.swing.JTextField XepThu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField lost_win;
    // End of variables declaration//GEN-END:variables
}
